// help_data/chemistry.js
// Converted from JovansCalculator/help_data/chemistry.lsp

_helpDb.push.apply(_helpDb, [
  { name:'ideal_gas_law', lispName:'ideal-gas-law', category:'Chemistry',
    parameters:'(pressure, volume, temperature, moles)', description:'Calculate missing parameter from ideal gas law PV = nRT. Pass null for the unknown.',
    example:'ideal_gas_law(null, 22.4, 273.15, 1.0)' },
  { name:'boyles_law', lispName:'boyles-law', category:'Chemistry',
    parameters:'(p1, v1, p2, v2)', description:"Calculate missing parameter using Boyle's Law: P1·V1 = P2·V2.",
    example:'boyles_law(1.0, 10.0, 2.0, null)' },
  { name:'charles_law', lispName:'charles-law', category:'Chemistry',
    parameters:'(v1, t1, v2, t2)', description:"Calculate missing parameter using Charles' Law: V1/T1 = V2/T2.",
    example:'charles_law(10.0, 300, null, 600)' },
  { name:'combined_gas_law', lispName:'combined-gas-law', category:'Chemistry',
    parameters:'(p1, v1, t1, p2, v2, t2)', description:'Calculate missing parameter using combined gas law.',
    example:'combined_gas_law(1.0, 10.0, 300, 2.0, null, 600)' },
  { name:'molarity', lispName:'molarity', category:'Chemistry',
    parameters:'(moles, volume_liters)', description:'Calculate molarity (M) = moles / liters.',
    example:'molarity(0.5, 2.0)' },
  { name:'molality', lispName:'molality', category:'Chemistry',
    parameters:'(moles, mass_solvent_kg)', description:'Calculate molality (m) = moles / kg solvent.',
    example:'molality(0.1, 1.0)' },
  { name:'mole_fraction', lispName:'mole-fraction', category:'Chemistry',
    parameters:'(moles_solute, moles_solvent)', description:'Calculate mole fraction of solute.',
    example:'mole_fraction(0.2, 1.8)' },
  { name:'dilution_equation', lispName:'dilution-equation', category:'Chemistry',
    parameters:'(c1, v1, c2, v2)', description:'Calculate missing parameter using C1·V1 = C2·V2.',
    example:'dilution_equation(1.0, 100, null, 500)' },
  { name:'mass_to_moles', lispName:'mass-to-moles', category:'Chemistry',
    parameters:'(mass, molecular_weight)', description:'Convert mass (g) to moles using molecular weight.',
    example:'mass_to_moles(18.0, 18.015)' },
  { name:'henderson_hasselbalch', lispName:'henderson-hasselbalch', category:'Chemistry',
    parameters:'(pka, conjugate_base_conc, weak_acid_conc)', description:'Calculate pH using Henderson–Hasselbalch equation.',
    example:'henderson_hasselbalch(4.76, 0.1, 0.1)' },
  { name:'ph_from_hydrogen_ion', lispName:'ph-from-hydrogen-ion', category:'Chemistry',
    parameters:'(hydrogen_ion_conc)', description:'Calculate pH from hydrogen ion concentration.',
    example:'ph_from_hydrogen_ion(1e-7)' },
  { name:'first_order_kinetics', lispName:'first-order-kinetics', category:'Chemistry',
    parameters:'(initial_conc, rate_constant, time)', description:'Calculate concentration after time t for first-order reaction.',
    example:'first_order_kinetics(1.0, 0.693, 1.0)' },
  { name:'half_life_first_order', lispName:'half-life-first-order', category:'Chemistry',
    parameters:'(rate_constant)', description:'Calculate half-life for first-order reaction.',
    example:'half_life_first_order(0.693)' },
  { name:'gibbs_free_energy', lispName:'gibbs-free-energy', category:'Chemistry',
    parameters:'(enthalpy, entropy, temperature)', description:'Calculate Gibbs free energy: ΔG = ΔH - TΔS.',
    example:'gibbs_free_energy(-100000, -50, 298)' },
  { name:'nernst_equation', lispName:'nernst-equation', category:'Chemistry',
    parameters:'(standard_potential, electron_count, reaction_quotient, temperature)', description:'Calculate cell potential using Nernst equation.',
    example:'nernst_equation(1.1, 2, 0.1, 298)' },
  { name:'beer_lambert_law', lispName:'beer-lambert-law', category:'Chemistry',
    parameters:'(molar_absorptivity, path_length, concentration)', description:'Calculate absorbance using Beer–Lambert law: A = εlc.',
    example:'beer_lambert_law(1000, 1.0, 0.001)' },
  { name:'bragg_law', lispName:'bragg-law', category:'Chemistry',
    parameters:'(n, wavelength, d_spacing, theta)', description:"Calculate missing parameter from Bragg's law: nλ = 2d sinθ. Pass null for unknown.",
    example:'bragg_law(1, null, 2.5e-10, 0.5236)' },
  { name:'associated_laguerre', lispName:'associated-laguerre', category:'Chemistry',
    parameters:'(n, alpha, x)', description:'Compute the associated Laguerre polynomial L_n^alpha(x).',
    example:'associated_laguerre(2, 1, 1.0)' },
  { name:'associated_legendre', lispName:'associated-legendre', category:'Chemistry',
    parameters:'(l, m, x)', description:'Compute the associated Legendre polynomial P_l^m(x).',
    example:'associated_legendre(2, 1, 0.5)' },
  { name:'spherical_harmonic_real', lispName:'spherical-harmonic-real', category:'Chemistry',
    parameters:'(l, m, theta, phi)', description:'Compute real-valued spherical harmonic Y_l^m(theta, phi).',
    example:'spherical_harmonic_real(1, 0, 0.5, 0.0)' },
  { name:'radial_wavefunction', lispName:'radial-wavefunction', category:'Chemistry',
    parameters:'(n, l, r)', description:'Compute the radial wavefunction R_nl(r) for a hydrogen-like atom (r in Bohr radii).',
    example:'radial_wavefunction(2, 1, 1.0)' },
  { name:'hydrogen_wavefunction_squared', lispName:'hydrogen-wavefunction-squared', category:'Chemistry',
    parameters:'(n, l, m, r, theta, phi)', description:'Compute |ψ_nlm|² probability density for a hydrogen atom.',
    example:'hydrogen_wavefunction_squared(1, 0, 0, 1.0, 0.5, 0.0)' },
  { name:'generate_orbital_points', lispName:'generate-orbital-points', category:'Chemistry',
    parameters:'(n, l, m, num_points=2000)', description:'Generate 3D point cloud for hydrogen orbital via rejection sampling. Returns {xs, ys, zs}.',
    example:'generate_orbital_points(2, 1, 0, 500)' },
  { name:'orbital_label', lispName:'orbital-label', category:'Chemistry',
    parameters:'(n, l, m)', description:"Generate a human-readable label (e.g. '2p (m=0)') for an orbital.",
    example:'orbital_label(3, 2, 0)' },
  { name:'calculate_molarity', lispName:'calculate-molarity', category:'Chemistry',
    parameters:'(moles_solute, volume_liters)', description:'Calculate the molarity of a solution.',
    example:'calculate_molarity(0.5, 1)' },
  { name:'calculate_ph', lispName:'calculate-ph', category:'Chemistry',
    parameters:'(h_plus_concentration)', description:'Calculate the pH of a solution from hydrogen ion concentration.',
    example:'calculate_ph(1e-7)' },
  { name:'calculate_gibbs_free_energy', lispName:'calculate-gibbs-free-energy', category:'Chemistry',
    parameters:'(delta_h, delta_s, temperature)', description:'Calculate the Gibbs free energy for a reaction.',
    example:'calculate_gibbs_free_energy(-92200, -198.7, 298)' },
  { name:'arrhenius_equation', lispName:'calculate-arrhenius-rate', category:'Chemistry',
    parameters:'(pre_exponential, activation_energy, temperature)', description:'Calculate rate constant using Arrhenius equation.',
    example:'arrhenius_equation(1e13, 83140, 300)' },
]);
