// help_data/electrical_engineering.js
// Converted from JovansCalculator/help_data/electrical_engineering.lsp

_helpDb.push.apply(_helpDb, [
  { name:'calculate_capacitance', lispName:'calculate-capacitance', category:'Electrical Engineering',
    parameters:'(area, k, thickness)', description:'Calculate the capacitance of a parallel plate capacitor.',
    example:'calculate_capacitance(1e-4, 4.5, 1e-6)' },
  { name:'calculate_capacitor_area', lispName:'calculate-capacitor-area', category:'Electrical Engineering',
    parameters:'(capacitance, k, thickness)', description:'Calculate the area of a capacitor given its capacitance.',
    example:'calculate_capacitor_area(1e-12, 4.5, 1e-6)' },
  { name:'calculate_capacitance_series', lispName:'calculate-capacitance-series', category:'Electrical Engineering',
    parameters:'(area1, area2, k1, k2, thickness1, thickness2)', description:'Calculate total capacitance for two capacitors in series.',
    example:'calculate_capacitance_series(1e-4, 2e-4, 3.9, 4.5, 1e-6, 2e-6)' },
  { name:'calculate_capacitance_parallel', lispName:'calculate-capacitance-parallel', category:'Electrical Engineering',
    parameters:'(area1, area2, k1, k2, thickness1, thickness2)', description:'Calculate total capacitance for two capacitors in parallel.',
    example:'calculate_capacitance_parallel(1e-4, 2e-4, 3.9, 4.5, 1e-6, 2e-6)' },
  { name:'calculate_capacitor_thickness', lispName:'calculate-capacitor-thickness', category:'Electrical Engineering',
    parameters:'(capacitance, k, area)', description:'Calculate the thickness of a parallel plate capacitor.',
    example:'calculate_capacitor_thickness(1e-12, 3.9, 1e-4)' },
  { name:'calculate_dielectric_constant', lispName:'calculate-dielectric-constant', category:'Electrical Engineering',
    parameters:'(capacitance, thickness, area)', description:'Calculate the dielectric constant of a capacitor material.',
    example:'calculate_dielectric_constant(1e-12, 1e-6, 1e-4)' },
  { name:'paschen_breakdown_voltage', lispName:'paschen-breakdown-voltage', category:'Electrical Engineering',
    parameters:'(pressure, gap)', description:"Calculate breakdown voltage using Paschen's law for gas discharge.",
    example:'paschen_breakdown_voltage(101.325, 1e-3)' },
  { name:'diode_current', lispName:'diode-current', category:'Electrical Engineering',
    parameters:'(v, is, n, vt, rs)', description:'Calculate diode current using the Shockley diode equation.',
    example:'diode_current(0.7, 1.0e-12, 1.5, 25.85e-3, 10)' },
  { name:'tungsten_probe_max_current', lispName:'tungsten-probe-max-current', category:'Electrical Engineering',
    parameters:'(diameter)', description:'Calculate maximum current for a tungsten probe based on diameter.',
    example:'tungsten_probe_max_current(25e-6)' },
  { name:'tungsten_max_power', lispName:'tungsten-max-power', category:'Electrical Engineering',
    parameters:'(length, diameter, t_ambient, t_max)', description:'Calculate maximum power for a tungsten probe via thermal limits.',
    example:'tungsten_max_power(1e-3, 25e-6, 300, 2000)' },
  { name:'tungsten_current_limit_geo', lispName:'tungsten-current-limit-geo', category:'Electrical Engineering',
    parameters:'(length, diameter, pmax)', description:'Calculate current limit based on tungsten probe geometry and power constraints.',
    example:'tungsten_current_limit_geo(1e-3, 25e-6, 0.1)' },
  { name:'copper_bulk_resistivity_fn', lispName:'copper-bulk-resistivity', category:'Electrical Engineering',
    parameters:'(temperature)', description:'Calculate copper bulk resistivity as a function of temperature.',
    example:'copper_bulk_resistivity_fn(300)' },
  { name:'copper_film_thickness', lispName:'copper-film-thickness', category:'Electrical Engineering',
    parameters:'(sheet_resistance)', description:'Calculate copper film thickness from sheet resistance measurement.',
    example:'copper_film_thickness(0.1)' },
  { name:'watts_to_dbm', lispName:'watts-to-dbm', category:'Electrical Engineering',
    parameters:'(power_watts)', description:'Convert power from Watts to dBm.',
    example:'watts_to_dbm(0.001)' },
  { name:'dbm_to_watts', lispName:'dbm-to-watts', category:'Electrical Engineering',
    parameters:'(power_dbm)', description:'Convert power from dBm to Watts.',
    example:'dbm_to_watts(0)' },
  { name:'reflection_coefficient', lispName:'reflection-coefficient', category:'Electrical Engineering',
    parameters:'(zload, z0)', description:'Calculate reflection coefficient Γ = (ZL - Z0)/(ZL + Z0).',
    example:'reflection_coefficient(75, 50)' },
  { name:'vswr_from_reflection', lispName:'vswr-from-reflection', category:'Electrical Engineering',
    parameters:'(gamma_magnitude)', description:'Calculate VSWR from reflection coefficient magnitude.',
    example:'vswr_from_reflection(0.2)' },
  { name:'return_loss', lispName:'return-loss', category:'Electrical Engineering',
    parameters:'(gamma_magnitude)', description:'Calculate return loss in dB from reflection coefficient magnitude.',
    example:'return_loss(0.1)' },
  { name:'characteristic_impedance', lispName:'characteristic-impedance', category:'Electrical Engineering',
    parameters:'(inductance_per_length, capacitance_per_length)', description:'Calculate characteristic impedance Z0 = sqrt(L/C).',
    example:'characteristic_impedance(2.5e-7, 1e-10)' },
  { name:'cable_loss', lispName:'cable-loss', category:'Electrical Engineering',
    parameters:'(loss_per_length, length_meters)', description:'Calculate total cable loss in dB.',
    example:'cable_loss(0.2, 10)' },
  { name:'quarter_wave_transformer_impedance', lispName:'quarter-wave-transformer-impedance', category:'Electrical Engineering',
    parameters:'(z1, z2)', description:'Calculate impedance of quarter-wave transformer for impedance matching.',
    example:'quarter_wave_transformer_impedance(50, 75)' },
  { name:'noise_figure_db', lispName:'noise-figure-db', category:'Electrical Engineering',
    parameters:'(signal_in, signal_out, noise_in, noise_out)', description:'Calculate noise figure in dB from signal and noise levels.',
    example:'noise_figure_db(1.0, 10.0, 0.01, 0.05)' },
  { name:'friis_noise_formula', lispName:'friis-noise-formula', category:'Electrical Engineering',
    parameters:'(nf1_db, nf2_db, gain1_db)', description:'Calculate total noise figure of cascaded amplifiers using Friis formula.',
    example:'friis_noise_formula(3.0, 6.0, 20.0)' },
  { name:'resonant_frequency_lc', lispName:'resonant-frequency-lc', category:'Electrical Engineering',
    parameters:'(inductance, capacitance)', description:'Calculate resonant frequency: f = 1/(2π√LC).',
    example:'resonant_frequency_lc(1e-6, 1e-9)' },
  { name:'free_space_path_loss', lispName:'free-space-path-loss', category:'Electrical Engineering',
    parameters:'(distance_km, frequency_mhz)', description:'Calculate free space path loss in dB.',
    example:'free_space_path_loss(1.0, 1000)' },
  { name:'effective_radiated_power', lispName:'effective-radiated-power', category:'Electrical Engineering',
    parameters:'(tx_power_dbm, antenna_gain_dbi, cable_loss_db)', description:'Calculate effective radiated power (ERP) in dBm.',
    example:'effective_radiated_power(30, 6, 2)' },
  { name:'link_budget', lispName:'link-budget', category:'Electrical Engineering',
    parameters:'(tx_power_dbm, tx_gain_dbi, rx_gain_dbi, path_loss_db, cable_losses_db)', description:'Calculate received power in RF link budget analysis.',
    example:'link_budget(30, 6, 6, 100, 3)' },
  { name:'dipole_length', lispName:'dipole-length', category:'Electrical Engineering',
    parameters:'(frequency_mhz)', description:'Calculate half-wave dipole antenna length in meters.',
    example:'dipole_length(100)' },
  { name:'tdr_distance_to_fault', lispName:'tdr-distance-to-fault', category:'Electrical Engineering',
    parameters:'(time_ns, velocity_factor)', description:'Calculate distance to fault from TDR measurement.',
    example:'tdr_distance_to_fault(100, 0.66)' },
  { name:'blanket_metal_resistance_colinear', lispName:'blanket-metal-resistance-colinear', category:'Electrical Engineering',
    parameters:'(sheet_res)', description:'Calculate resistance of a thin metal film over a large area.',
    example:'blanket_metal_resistance_colinear(0.31)' },
]);
