// help_data/mathematical.js — Help entries for Mathematical functions
// Converted from JovansCalculator/help_data/mathematical.lsp

_helpDb.push.apply(_helpDb, [
  { name:'symbolic_derivative', lispName:'symbolic-derivative', category:'Mathematical',
    parameters:'(expr, var)', description:'Calculate the symbolic derivative of a polynomial expression with respect to a variable.',
    example:"symbolic_derivative(['+', ['*',3,['expt','x',2]], ['*',2,'x']], 'x')" },
  { name:'simplify', lispName:'simplify', category:'Mathematical',
    parameters:'(expr)', description:'Simplify mathematical expressions by removing zero terms and combining constants.',
    example:"simplify(['+', ['*',0,'x'], ['*',1,'y']])" },
  { name:'group_terms', lispName:'group-terms', category:'Mathematical',
    parameters:'(expr)', description:'Group like terms in an expression and combine their coefficients.',
    example:"group_terms(['+', ['*',2,'x'], ['*',3,'x'], 5])" },
  { name:'infix_notation', lispName:'infix-notation', category:'Mathematical',
    parameters:'(expr)', description:'Convert nested-array prefix expressions to a readable infix notation string.',
    example:"infix_notation(['+', ['*',3,['expt','x',2]], ['*',2,'x'], 1])" },
  { name:'pretty_print_expression', lispName:'pretty-print-expression', category:'Mathematical',
    parameters:'(expr)', description:'Pretty print a mathematical expression in infix notation to console.',
    example:"pretty_print_expression(['/', ['+','a','b'], ['-','c','d']])" },
  { name:'latex_notation', lispName:'latex-notation', category:'Mathematical',
    parameters:'(expr)', description:'Convert prefix expressions to LaTeX mathematical notation.',
    example:"latex_notation(['/', ['+','a','b'], ['*','c','d']])" },
  { name:'derivative_step_by_step', lispName:'derivative-step-by-step', category:'Mathematical',
    parameters:'(expr, var)', description:'Show step-by-step derivative calculation with explanations and infix output.',
    example:"derivative_step_by_step(['*',3,['expt','x',2]], 'x')" },
  { name:'make_polynomial', lispName:'make-polynomial', category:'Mathematical',
    parameters:'(coeffs, var)', description:'Create a polynomial expression from a list of coefficients (lowest degree first).',
    example:"make_polynomial([1,2,3], 'x')" },
  { name:'polynomial_degree', lispName:'polynomial-degree', category:'Mathematical',
    parameters:'(coeffs)', description:'Return the degree of a polynomial given its coefficient list (lowest degree first).',
    example:'polynomial_degree([1,2,3,0])' },
  { name:'evaluate_polynomial', lispName:'evaluate-polynomial', category:'Mathematical',
    parameters:'(coeffs, x_val)', description:"Evaluate a polynomial at a given point using Horner's method.",
    example:'evaluate_polynomial([1,2,3], 2)' },
  { name:'polynomial_add', lispName:'polynomial-add', category:'Mathematical',
    parameters:'(coeffs1, coeffs2)', description:'Add two polynomials represented as coefficient lists.',
    example:'polynomial_add([1,2], [3,4,5])' },
  { name:'polynomial_multiply', lispName:'polynomial-multiply', category:'Mathematical',
    parameters:'(coeffs1, coeffs2)', description:'Multiply two polynomials represented as coefficient lists.',
    example:'polynomial_multiply([1,1], [1,-1])' },
  { name:'make_affine_curve', lispName:'make-affine-curve', category:'Mathematical',
    parameters:'(poly, vars)', description:'Create an affine algebraic curve f(x,y)=0 representation.',
    example:"make_affine_curve(['-', ['expt','y',2], ['expt','x',3]], ['x','y'])" },
  { name:'make_projective_curve', lispName:'make-projective-curve', category:'Mathematical',
    parameters:'(poly, vars)', description:'Create a projective algebraic curve from a homogeneous polynomial.',
    example:"make_projective_curve(['-', ['*','y','y','z'], ['expt','x',3]], ['x','y','z'])" },
  { name:'curve_polynomial', lispName:'curve-polynomial', category:'Mathematical',
    parameters:'(curve)', description:'Extract the defining polynomial from a curve.',
    example:'curve_polynomial(my_curve)' },
  { name:'curve_variables', lispName:'curve-variables', category:'Mathematical',
    parameters:'(curve)', description:'Extract the variables from a curve definition.',
    example:'curve_variables(my_curve)' },
  { name:'homogenize_polynomial', lispName:'homogenize-polynomial', category:'Mathematical',
    parameters:"(poly, var_x, var_y, var_z, degree)", description:"Homogenize a polynomial in x,y by introducing z.",
    example:"homogenize_polynomial(['+','x',1], 'x','y','z', 2)" },
  { name:'make_elliptic_curve', lispName:'make-elliptic-curve', category:'Mathematical',
    parameters:'(a, b)', description:'Create an elliptic curve in Weierstrass form: y² = x³ + ax + b.',
    example:'make_elliptic_curve(-1, 0)' },
  { name:'elliptic_curve_discriminant', lispName:'elliptic-curve-discriminant', category:'Mathematical',
    parameters:'(a, b)', description:'Calculate the discriminant of an elliptic curve y² = x³ + ax + b.',
    example:'elliptic_curve_discriminant(-1, 0)' },
  { name:'elliptic_curve_j_invariant', lispName:'elliptic-curve-j-invariant', category:'Mathematical',
    parameters:'(a, b)', description:'Calculate the j-invariant of an elliptic curve.',
    example:'elliptic_curve_j_invariant(-1, 0)' },
  { name:'elliptic_point_on_curve_p', lispName:'elliptic-point-on-curve-p', category:'Mathematical',
    parameters:'(x, y, a, b)', description:'Check if point (x,y) lies on elliptic curve y² = x³ + ax + b.',
    example:'elliptic_point_on_curve_p(0, 0, -1, 0)' },
  { name:'elliptic_curve_add', lispName:'elliptic-curve-add', category:'Mathematical',
    parameters:'(p1, p2, a, b)', description:'Add two points on an elliptic curve using the group law.',
    example:"elliptic_curve_add({x:0,y:0}, {x:1,y:0}, -1, 0)" },
  { name:'elliptic_curve_scalar_mult', lispName:'elliptic-curve-scalar-mult', category:'Mathematical',
    parameters:'(n, p, a, b)', description:'Scalar multiplication n*P on an elliptic curve.',
    example:"elliptic_curve_scalar_mult(3, {x:1,y:0}, -1, 0)" },
  { name:'bezout_number', lispName:'bezout-number', category:'Mathematical',
    parameters:'(deg1, deg2)', description:'Calculate the Bézout number (intersection count) for curves of given degrees.',
    example:'bezout_number(2, 3)' },
  { name:'genus_smooth_plane_curve', lispName:'genus-smooth-plane-curve', category:'Mathematical',
    parameters:'(degree)', description:'Calculate the genus of a smooth plane curve: g = (d-1)(d-2)/2.',
    example:'genus_smooth_plane_curve(3)' },
  { name:'euler_characteristic_surface', lispName:'euler-characteristic-surface', category:'Mathematical',
    parameters:'(genus)', description:'Calculate the Euler characteristic: chi = 2 - 2g.',
    example:'euler_characteristic_surface(1)' },
  { name:'arithmetic_genus', lispName:'arithmetic-genus', category:'Mathematical',
    parameters:'(degree, dimension)', description:'Calculate the arithmetic genus of a hypersurface of degree d in Pⁿ.',
    example:'arithmetic_genus(3, 2)' },
  { name:'affine_to_projective', lispName:'affine-to-projective', category:'Mathematical',
    parameters:'(x, y)', description:'Convert affine coordinates (x,y) to projective coordinates [x:y:1].',
    example:'affine_to_projective(2, 3)' },
  { name:'projective_to_affine', lispName:'projective-to-affine', category:'Mathematical',
    parameters:'(coords)', description:'Convert projective coordinates [x:y:z] to affine (x/z, y/z).',
    example:'projective_to_affine([2, 4, 2])' },
  { name:'projective_line_through_points', lispName:'projective-line-through-points', category:'Mathematical',
    parameters:'(p1, p2)', description:'Find the projective line through two points in P².',
    example:'projective_line_through_points([1,0,1], [0,1,1])' },
  { name:'projective_intersection', lispName:'projective-intersection', category:'Mathematical',
    parameters:'(line1, line2)', description:'Find the intersection point of two projective lines.',
    example:'projective_intersection([1,0,0], [0,1,0])' },
  { name:'cross_ratio', lispName:'cross-ratio', category:'Mathematical',
    parameters:'(p1, p2, p3, p4)', description:'Calculate the cross-ratio of four collinear points.',
    example:'cross_ratio(0, 1, 2, 3)' },
  { name:'milnor_number', lispName:'milnor-number', category:'Mathematical',
    parameters:'(singularity_type)', description:"Return the Milnor number for common singularity types (node, cusp, 'E6', etc.).",
    example:"milnor_number('cusp')" },
  { name:'hilbert_polynomial_curve', lispName:'hilbert-polynomial-curve', category:'Mathematical',
    parameters:'(degree)', description:'Return the Hilbert polynomial function of a plane curve.',
    example:'hilbert_polynomial_curve(3)(5)' },
  { name:'dimension_linear_system', lispName:'dimension-linear-system', category:'Mathematical',
    parameters:'(degree, genus, num_points)', description:'Estimate dimension of linear system |D| using Riemann-Roch.',
    example:'dimension_linear_system(5, 1, 0)' },
]);
