// help_data/matrix_operations.js
// Converted from JovansCalculator/help_data/matrix_operations.lsp (selected entries)

_helpDb.push.apply(_helpDb, [
  { name:'make_matrix', lispName:'make-matrix', category:'Matrix Operations',
    parameters:'(n, m, list)', description:'Create a matrix with n rows, m cols from a flat array.',
    example:'make_matrix(2, 3, [1,2,3,4,5,6])' },
  { name:'identity_matrix', lispName:'identity-matrix', category:'Matrix Operations',
    parameters:'(n)', description:'Create an n×n identity matrix.',
    example:'identity_matrix(3)' },
  { name:'zero_matrix', lispName:'zero-matrix', category:'Matrix Operations',
    parameters:'(n, m)', description:'Create an n×m matrix of zeros.',
    example:'zero_matrix(2, 3)' },
  { name:'ones_matrix', lispName:'ones-matrix', category:'Matrix Operations',
    parameters:'(n, m)', description:'Create an n×m matrix of ones.',
    example:'ones_matrix(2, 3)' },
  { name:'diagonal_matrix', lispName:'diagonal-matrix', category:'Matrix Operations',
    parameters:'(diag_list)', description:'Create a square diagonal matrix from a list of diagonal entries.',
    example:'diagonal_matrix([1, 2, 3])' },
  { name:'random_matrix', lispName:'random-matrix', category:'Matrix Operations',
    parameters:'(n, m)', description:'Create an n×m matrix with uniform random entries in [0,1).',
    example:'random_matrix(3, 3)' },
  { name:'hilbert_matrix', lispName:'hilbert-matrix', category:'Matrix Operations',
    parameters:'(n)', description:'Create an n×n Hilbert matrix H(i,j) = 1/(i+j+1).',
    example:'hilbert_matrix(4)' },
  { name:'vandermonde_matrix', lispName:'vandermonde-matrix', category:'Matrix Operations',
    parameters:'(vec)', description:'Create a Vandermonde matrix from a vector.',
    example:'vandermonde_matrix([1,2,3])' },
  { name:'matrix_rows', lispName:'matrix-rows', category:'Matrix Operations',
    parameters:'(mat)', description:'Return the number of rows in a matrix.',
    example:'matrix_rows(A)' },
  { name:'matrix_cols', lispName:'matrix-cols', category:'Matrix Operations',
    parameters:'(mat)', description:'Return the number of columns in a matrix.',
    example:'matrix_cols(A)' },
  { name:'matrix_trace', lispName:'matrix-trace', category:'Matrix Operations',
    parameters:'(mat)', description:'Calculate the trace (sum of diagonal elements) of a square matrix.',
    example:'matrix_trace(A)' },
  { name:'matrix_determinant', lispName:'matrix-determinant', category:'Matrix Operations',
    parameters:'(mat)', description:'Calculate the determinant of a square matrix.',
    example:'matrix_determinant(A)' },
  { name:'matrix_add', lispName:'matrix-add', category:'Matrix Operations',
    parameters:'(a, b)', description:'Add two matrices element-wise.',
    example:'matrix_add(A, B)' },
  { name:'matrix_subtract', lispName:'matrix-subtract', category:'Matrix Operations',
    parameters:'(a, b)', description:'Subtract matrix b from matrix a element-wise.',
    example:'matrix_subtract(A, B)' },
  { name:'matrix_scale', lispName:'matrix-scale', category:'Matrix Operations',
    parameters:'(scalar, mat)', description:'Multiply every element of a matrix by a scalar.',
    example:'matrix_scale(2, A)' },
  { name:'matrix_multiply', lispName:'matrix-multiply', category:'Matrix Operations',
    parameters:'(a, b)', description:'Multiply two matrices.',
    example:'matrix_multiply(A, B)' },
  { name:'matrix_transpose', lispName:'matrix-transpose', category:'Matrix Operations',
    parameters:'(mat)', description:'Transpose a matrix.',
    example:'matrix_transpose(A)' },
  { name:'matrix_inverse', lispName:'matrix-inverse', category:'Matrix Operations',
    parameters:'(mat)', description:'Compute the inverse of a square matrix.',
    example:'matrix_inverse(A)' },
  { name:'matrix_power', lispName:'matrix-power', category:'Matrix Operations',
    parameters:'(mat, n)', description:'Raise a square matrix to the nth power.',
    example:'matrix_power(A, 3)' },
  { name:'commutator', lispName:'commutator', category:'Matrix Operations',
    parameters:'(a, b)', description:'Compute the commutator [A, B] = AB - BA.',
    example:'commutator(A, B)' },
  { name:'matrix_row', lispName:'matrix-row', category:'Matrix Operations',
    parameters:'(mat, i)', description:'Extract row i of a matrix as an array.',
    example:'matrix_row(A, 0)' },
  { name:'matrix_column', lispName:'matrix-column', category:'Matrix Operations',
    parameters:'(mat, j)', description:'Extract column j of a matrix as an array.',
    example:'matrix_column(A, 0)' },
  { name:'matrix_diagonal', lispName:'matrix-diagonal', category:'Matrix Operations',
    parameters:'(mat)', description:'Extract the main diagonal of a matrix.',
    example:'matrix_diagonal(A)' },
  { name:'is_symmetric_p', lispName:'is-symmetric-p', category:'Matrix Operations',
    parameters:'(mat, tol=1e-10)', description:'Check if a matrix is symmetric within tolerance.',
    example:'is_symmetric_p(A)' },
  { name:'is_orthogonal_p', lispName:'is-orthogonal-p', category:'Matrix Operations',
    parameters:'(mat, tol=1e-10)', description:'Check if a matrix is orthogonal: Aᵀ·A = I.',
    example:'is_orthogonal_p(Q)' },
  { name:'is_positive_definite_p', lispName:'is-positive-definite-p', category:'Matrix Operations',
    parameters:'(mat)', description:'Check if a symmetric matrix is positive definite.',
    example:'is_positive_definite_p(A)' },
  { name:'matrix_rank_estimate', lispName:'matrix-rank-estimate', category:'Matrix Operations',
    parameters:'(mat, tol=1e-10)', description:'Estimate the rank of a matrix using SVD.',
    example:'matrix_rank_estimate(A)' },
  { name:'display_matrix', lispName:'display-matrix', category:'Matrix Operations',
    parameters:'(mat)', description:'Display a matrix in formatted tabular form.',
    example:'display_matrix(A)' },
  { name:'gram_schmidt_matrix', lispName:'gram-schmidt-matrix', category:'Matrix Operations',
    parameters:'(mat)', description:'Orthogonalize matrix columns via Gram-Schmidt.',
    example:'gram_schmidt_matrix(A)' },
  { name:'rotation_matrix_2d', lispName:'rotation-matrix-2d', category:'Matrix Operations',
    parameters:'(angle)', description:'Create a 2D rotation matrix for given angle (radians).',
    example:'rotation_matrix_2d(Math.PI/4)' },
  { name:'rotation_matrix_z', lispName:'rotation-matrix-z', category:'Matrix Operations',
    parameters:'(angle)', description:'Create a 3D rotation matrix about the z-axis.',
    example:'rotation_matrix_z(Math.PI/2)' },
  { name:'covariance_matrix', lispName:'covariance-matrix', category:'Matrix Operations',
    parameters:'(data_matrix)', description:'Compute sample covariance matrix from data (rows = observations).',
    example:'covariance_matrix(data)' },
  { name:'principal_components', lispName:'principal-components', category:'Matrix Operations',
    parameters:'(data_matrix, k)', description:'Return top-k principal components of data.',
    example:'principal_components(data, 2)' },
  { name:'linspace_vector', lispName:'linspace-vector', category:'Matrix Operations',
    parameters:'(start, end, n)', description:'Create an array of n evenly spaced values from start to end.',
    example:'linspace_vector(0, 1, 10)' },
  { name:'range_vector', lispName:'range-vector', category:'Matrix Operations',
    parameters:'(start, end, step=1)', description:'Create an array from start to end (exclusive) with given step.',
    example:'range_vector(0, 10, 2)' },
]);
