// help_data/quantum_physics.js
// Converted from JovansCalculator/help_data/quantum_physics.lsp

_helpDb.push.apply(_helpDb, [
  { name:'calculate_bohr_radius', lispName:'calculate-bohr-radius', category:'Quantum Physics',
    parameters:'(n, z)', description:'Calculate the Bohr radius for a hydrogen-like atom.',
    example:'calculate_bohr_radius(1, 1)' },
  { name:'calculate_energy_level', lispName:'calculate-energy-level', category:'Quantum Physics',
    parameters:'(n, z)', description:'Calculate the energy level of a hydrogen-like atom.',
    example:'calculate_energy_level(1, 1)' },
  { name:'calculate_photon_energy', lispName:'calculate-photon-energy', category:'Quantum Physics',
    parameters:'(lambda)', description:'Calculate the energy of a photon given its wavelength.',
    example:'calculate_photon_energy(500e-9)' },
  { name:'calculate_photon_wavelength', lispName:'calculate-photon-wavelength', category:'Quantum Physics',
    parameters:'(energy)', description:'Calculate the wavelength of a photon given its energy.',
    example:'calculate_photon_wavelength(2.48e-19)' },
  { name:'calculate_de_broglie_wavelength', lispName:'calculate-de-broglie-wavelength', category:'Quantum Physics',
    parameters:'(mass, velocity)', description:'Calculate the de Broglie wavelength of a particle.',
    example:'calculate_de_broglie_wavelength(9.109e-31, 1e6)' },
  { name:'calculate_tunneling_probability', lispName:'calculate-tunneling-probability', category:'Quantum Physics',
    parameters:'(v0, e, width, mass)', description:'Calculate the tunneling probability through a rectangular barrier.',
    example:'calculate_tunneling_probability(10, 5, 1e-10, 9.109e-31)' },
  { name:'calculate_coulomb_force', lispName:'calculate-coulomb-force', category:'Quantum Physics',
    parameters:'(q1, q2, r)', description:'Calculate the Coulomb force between two point charges.',
    example:'calculate_coulomb_force(1.602e-19, -1.602e-19, 5.29e-11)' },
  { name:'calculate_electric_field', lispName:'calculate-electric-field', category:'Quantum Physics',
    parameters:'(q, r)', description:'Calculate the electric field due to a point charge.',
    example:'calculate_electric_field(1.602e-19, 5.29e-11)' },
  { name:'calculate_magnetic_field', lispName:'calculate-magnetic-field', category:'Quantum Physics',
    parameters:'(current, distance)', description:'Calculate the magnetic field due to a current-carrying wire.',
    example:'calculate_magnetic_field(1, 0.1)' },
  { name:'calculate_planck_length', lispName:'calculate-planck-length', category:'Quantum Physics',
    parameters:'()', description:'Calculate the Planck length.',
    example:'calculate_planck_length()' },
  { name:'calculate_planck_mass', lispName:'calculate-planck-mass', category:'Quantum Physics',
    parameters:'()', description:'Calculate the Planck mass.',
    example:'calculate_planck_mass()' },
  { name:'calculate_planck_time', lispName:'calculate-planck-time', category:'Quantum Physics',
    parameters:'()', description:'Calculate the Planck time.',
    example:'calculate_planck_time()' },
  { name:'calculate_planck_temperature', lispName:'calculate-planck-temperature', category:'Quantum Physics',
    parameters:'()', description:'Calculate the Planck temperature.',
    example:'calculate_planck_temperature()' },
  { name:'calculate_schwarzschild_radius', lispName:'calculate-schwarzschild-radius', category:'Quantum Physics',
    parameters:'(mass)', description:'Calculate the Schwarzschild radius of a black hole.',
    example:'calculate_schwarzschild_radius(1.989e30)' },
  { name:'calculate_hawking_temperature', lispName:'calculate-hawking-temperature', category:'Quantum Physics',
    parameters:'(mass)', description:'Calculate the Hawking temperature of a black hole.',
    example:'calculate_hawking_temperature(1.989e30)' },
  { name:'calculate_gravitational_force', lispName:'calculate-gravitational-force', category:'Quantum Physics',
    parameters:'(m1, m2, r)', description:'Calculate the gravitational force between two masses.',
    example:'calculate_gravitational_force(5.972e24, 1.989e30, 1.496e11)' },
  { name:'calculate_escape_velocity', lispName:'calculate-escape-velocity', category:'Quantum Physics',
    parameters:'(mass, radius)', description:'Calculate the escape velocity from a celestial body.',
    example:'calculate_escape_velocity(5.972e24, 6.371e6)' },
  { name:'calculate_time_dilation', lispName:'calculate-time-dilation', category:'Quantum Physics',
    parameters:'(velocity)', description:'Calculate the time dilation factor for a given velocity.',
    example:'calculate_time_dilation(0.99)' },
  { name:'calculate_length_contraction', lispName:'calculate-length-contraction', category:'Quantum Physics',
    parameters:'(length, velocity)', description:'Calculate the length contraction for a given velocity.',
    example:'calculate_length_contraction(1, 0.99)' },
  { name:'calculate_relativistic_mass', lispName:'calculate-relativistic-mass', category:'Quantum Physics',
    parameters:'(mass, velocity)', description:'Calculate the relativistic mass for a given velocity.',
    example:'calculate_relativistic_mass(1, 0.99)' },
  { name:'calculate_mass_energy_equivalence', lispName:'calculate-mass-energy-equivalence', category:'Quantum Physics',
    parameters:'(mass)', description:'Calculate the energy equivalent of a given mass (E = mc²).',
    example:'calculate_mass_energy_equivalence(1)' },
  { name:'hydrogen_ionization_energy', lispName:'hydrogen-ionization-energy', category:'Quantum Physics',
    parameters:'(n)', description:'Calculate ionization energy from hydrogen level n.',
    example:'hydrogen_ionization_energy(3)' },
  { name:'bohr_radius', lispName:'bohr-radius', category:'Quantum Physics',
    parameters:'(n)', description:'Calculate Bohr radius for nth orbital in hydrogen atom.',
    example:'bohr_radius(2)' },
  { name:'orbital_velocity', lispName:'orbital-velocity', category:'Quantum Physics',
    parameters:'(n)', description:'Calculate orbital velocity of electron in nth Bohr orbit.',
    example:'orbital_velocity(1)' },
  { name:'quantum_harmonic_oscillator_energy', lispName:'quantum-harmonic-oscillator-energy', category:'Quantum Physics',
    parameters:'(n)', description:'Calculate energy levels of quantum harmonic oscillator.',
    example:'quantum_harmonic_oscillator_energy(0)' },
  { name:'particle_in_box_energy', lispName:'particle-in-box-energy', category:'Quantum Physics',
    parameters:'(n, length, mass)', description:'Calculate energy levels for particle in 1D infinite square well.',
    example:'particle_in_box_energy(1, 1e-9, 9.109e-31)' },
  { name:'tunnel_probability', lispName:'tunnel-probability', category:'Quantum Physics',
    parameters:'(barrier_width, barrier_height, particle_energy, mass)', description:'Calculate quantum tunneling probability through rectangular barrier.',
    example:'tunnel_probability(1e-10, 5e-19, 1e-19, 9.109e-31)' },
  { name:'wavefunction_probability', lispName:'wavefunction-probability', category:'Quantum Physics',
    parameters:'(amplitude)', description:'Calculate probability density |ψ|² from wavefunction amplitude.',
    example:'wavefunction_probability({re:0.7071, im:0.7071})' },
  { name:'normalize_wavefunction', lispName:'normalize-wavefunction', category:'Quantum Physics',
    parameters:'(amplitudes)', description:'Normalize a list of wavefunction amplitudes.',
    example:'normalize_wavefunction([{re:1,im:0}, {re:1,im:1}, {re:0,im:1}])' },
  { name:'uncertainty_principle', lispName:'uncertainty-principle', category:'Quantum Physics',
    parameters:'(delta_x, delta_p)', description:'Check if uncertainty principle Δx·Δp ≥ ℏ/2 is satisfied.',
    example:'uncertainty_principle(1e-10, 1e-24)' },
  { name:'compton_wavelength', lispName:'compton-wavelength', category:'Quantum Physics',
    parameters:'(mass)', description:'Calculate Compton wavelength λ_c = h/(mc).',
    example:'compton_wavelength(9.109e-31)' },
  { name:'compton_scattering_wavelength', lispName:'compton-scattering-wavelength', category:'Quantum Physics',
    parameters:'(initial_wavelength, theta)', description:'Calculate wavelength after Compton scattering at angle theta.',
    example:'compton_scattering_wavelength(1e-12, Math.PI/2)' },
  { name:'blackbody_energy_density', lispName:'blackbody-energy-density', category:'Quantum Physics',
    parameters:'(temperature, frequency)', description:'Calculate energy density for blackbody radiation at given frequency.',
    example:'blackbody_energy_density(300, 5e14)' },
  { name:'wien_displacement_law', lispName:'wien-displacement-law', category:'Quantum Physics',
    parameters:'(temperature)', description:'Calculate peak wavelength for blackbody at given temperature.',
    example:'wien_displacement_law(5778)' },
  { name:'stefan_boltzmann_law', lispName:'stefan-boltzmann-law', category:'Quantum Physics',
    parameters:'(temperature)', description:'Calculate total radiated power per unit area using Stefan–Boltzmann law.',
    example:'stefan_boltzmann_law(300)' },
  { name:'zeeman_energy', lispName:'zeeman-energy', category:'Quantum Physics',
    parameters:'(magnetic_field, ms, g_factor)', description:'Calculate energy shift in magnetic field (Zeeman effect).',
    example:'zeeman_energy(1.0, 0.5, 2.0)' },
  { name:'paschen_wavelength', lispName:'paschen-wavelength', category:'Quantum Physics',
    parameters:'(n)', description:'Calculate wavelength for the Paschen series in nanometers.',
    example:'paschen_wavelength(4)' },
  { name:'pauli_matrices', lispName:'pauli-matrices', category:'Quantum Physics',
    parameters:'()', description:'Return the three Pauli matrices as an array.',
    example:'pauli_matrices()' },
  { name:'braiding_matrix', lispName:'braiding-matrix', category:'Quantum Physics',
    parameters:'(sigma)', description:'Generate braiding matrix for non-Abelian statistics.',
    example:'braiding_matrix(1)' },
  { name:'simulate_braiding', lispName:'simulate-braiding', category:'Quantum Physics',
    parameters:'()', description:'Simulate braiding operations in non-Abelian systems.',
    example:'simulate_braiding()' },
]);
